### ISSUE TITLE
Pop Shop details extension ibroke with the latest GNOME shell update

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-shell-extension-pop-shop-details#2]

**Comment by jackpot51** [comment]
This was not due to GNOME Shell. This was due to to cleanup to be closer to upstream AppCenter. They suggested that we do not change the name of the binary and DBUS to org.pop.shop from io.elementary.appcenter.

This issue will be fixed by https://github.com/pop-os/gnome-shell-extension-pop-shop-details/commit/7e3c05cd47490cf640abe684177c7e9078374532, and will be released once it hits proposed and is tested.

**Comment by jackpot51** [comment]
@brs17 Please install proposed when this build completes: http://10.17.75.78:8080/job/pop-os/job/repos/3731/console

Verify that right clicking on an application in GNOME Shell will have a "Show Details" item, and clicking it will launch Pop Shop.

**Comment by brs17** [comment]
@jackpot51 Looks good to me! :+1:

**Comment by jackpot51** [comment]
The fix is now released
